language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
  - USE_OPTIONAL=false
  - TRAVIS_PIP_VERSION=6.0.8
  - SETUPTOOLS_VERSION=10.2.1
  matrix:
  # TRAVIS_PIP_VERSION=1.1
  # TRAVIS_PIP_VERSION=1.2.1
  # TRAVIS_PIP_VERSION=1.3.1
  # TRAVIS_PIP_VERSION=1.4.1
  # TRAVIS_PIP_VERSION=1.5.6
  - TRAVIS_PIP_VERSION=6.0
  - TRAVIS_PIP_VERSION=6.0.8
  - TRAVIS_PIP_VERSION=6.1.1
  - TRAVIS_PIP_VERSION=7.0.3
  - TRAVIS_PIP_VERSION=7.1.2
  - TRAVIS_PIP_VERSION=8.0.3
  - TRAVIS_PIP_VERSION=8.1.2
  - SETUPTOOLS_VERSION=3.3
  - SETUPTOOLS_VERSION=3.8.1
  - SETUPTOOLS_VERSION=4.0.1
  - SETUPTOOLS_VERSION=5.8
  - SETUPTOOLS_VERSION=6.1
  - SETUPTOOLS_VERSION=7.0
  - SETUPTOOLS_VERSION=8.3
  - SETUPTOOLS_VERSION=9.1
  - SETUPTOOLS_VERSION=10.2.1
  - SETUPTOOLS_VERSION=11.3.1
  - SETUPTOOLS_VERSION=12
  - SETUPTOOLS_VERSION=13.0.2
  - SETUPTOOLS_VERSION=14.3
  - SETUPTOOLS_VERSION=15.2
  - SETUPTOOLS_VERSION=16.0
  - SETUPTOOLS_VERSION=17.1.1
  - SETUPTOOLS_VERSION=18.4
  - SETUPTOOLS_VERSION=18.5  # -8 all fail according to https://gsnedders.github.io/python-marker-test/results.html
  - SETUPTOOLS_VERSION=19.0  # also fails, but was fixed in 19.1
  - SETUPTOOLS_VERSION=19.1
  - SETUPTOOLS_VERSION=19.7
  - SETUPTOOLS_VERSION=20.10.1
  - SETUPTOOLS_VERSION=21.2.2
  - SETUPTOOLS_VERSION=22.0.5
  - SETUPTOOLS_VERSION=23.2.1
  - SETUPTOOLS_VERSION=24.0
  - SETUPTOOLS_VERSION=24.0.3

before_install:
  - git submodule update --init --recursive
  # Save the setuptools version
  - ORIG_SETUPTOOLS_VERSION=`python -c "import setuptools; print('%s' % setuptools.__version__)"`
  - echo setuptools $ORIG_SETUPTOOLS_VERSION
  - pip --version
  - pip install --upgrade pip==$TRAVIS_PIP_VERSION setuptools==$SETUPTOOLS_VERSION

install:
  - bash requirements-install.sh

script:
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then py.test; fi
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run -m pytest; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then bash flake8-run.sh; fi

after_script:
  - python debug-info.py

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage combine && codecov; fi
