language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

sudo: false

cache: pip

env:
  - USE_OPTIONAL=true
  - USE_OPTIONAL=false
  - SIX_VERSION=1.9 USE_OPTIONAL=true

install:
  - ./requirements-install.sh

script:
  - coverage run -m pytest
  - bash flake8-run.sh

after_script:
  - python debug-info.py

after_success:
  - codecov
