language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

env:
  - USE_OPTIONAL=true TOXENV=optional
  - USE_OPTIONAL=false TOXENV=base

before_install:
  - git submodule update --init --recursive

install:
  - pip install tox codecov

script:
  - tox
  - codecov

after_script:
  - python debug-info.py

after_success:
  # codecov
