language: python
python:
  - "3.2"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

env:
  - USE_OPTIONAL=true TOXENV=optional
  - USE_OPTIONAL=false TOXENV=base

before_install:
  - git submodule update --init --recursive

install:
  - pip install tox-travis codecov

script:
  - tox
  - codecov

after_script:
  - python debug-info.py

after_success:
  # codecov
